title: "Estatística Aplicada a Ciências Ambientais"
description: "Implementações em R como suporte para as aulas"
url: "https://detzeldhm.github.io/estatistica_ciencias_ambientais/"
theme: jekyll-theme-slate
